In [12]:
# Import the required libraries
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

In [14]:
df = pd.read_csv('iris.csv') 
df.head()  # Show the first 5 rows

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
df = pd.DataFrame(iris['data'])
df.head()

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [18]:
df[4] = iris['target']
df.head()

     0    1    2    3  4
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0
4  5.0  3.6  1.4  0.2  0

In [20]:
df.describe()

                0           1           2           3           4
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [22]:
# Adding column names
df.rename(columns = {0:'SepalLengthCm', 1:'SepalWidthCm', 2:'PetalLengthCm', 3:'PetalWidthCm', 4:'Species'}, inplace = True)
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [24]:
df.shape

(150, 5)

In [26]:
df.mean()

SepalLengthCm    5.843333
SepalWidthCm     3.057333
PetalLengthCm    3.758000
PetalWidthCm     1.199333
Species          1.000000
dtype: float64

In [30]:
df.median()

SepalLengthCm    5.80
SepalWidthCm     3.00
PetalLengthCm    4.35
PetalWidthCm     1.30
Species          1.00
dtype: float64

In [32]:
df.Species.mode()

0    0
1    1
2    2
Name: Species, dtype: int64

In [34]:
df.groupby(['Species']).count()

         SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
0                   50            50             50            50
1                   50            50             50            50
2                   50            50             50            50

STANDARD DEVIATION

In [37]:
df.SepalLengthCm.std()

0.8280661279778629

In [39]:
df.SepalWidthCm.std()

0.435866284936698

In [41]:
df.PetalLengthCm.std()

1.7652982332594667

In [43]:
df.PetalWidthCm.std()

0.7622376689603465